# Generated by Django 2.1 on 2018-08-19 12:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Product', '0002_auto_20180819_1447'),
    ]

    operations = [
        migrations.RenameField(
            model_name='product',
            old_name='title',
            new_name='name',
        ),
        migrations.AddField(
            model_name='product',
            name='description',
            field=models.TextField(default=True),
        ),
    ]
